function plotStim(Channel,StimNumber, StimStartIndex, StimEndIndex, AllData, AllTime, NumStims, varargin )
%
%plotStim plots the stimulation poststimulation and prestimulation
%in NeuroPace RNS Data given a Matrix AllData with Voltage data across
%channels and AllTime with corresponding time stamps to Voltage Data.
%
% plotStim(1,1,StimStartIndex,StimEndIndex,AllData,AllTime)
% 
% Inputs
%
% Channel- The channel you want to plot
% StimNumber- The number of the stimulation group you want to plot
% StimStartIndex- The index of stim start points generated by findStim
% StimEndIndex- The index of stim end points generated by findStim
% AllData-an (nxm) matrix with time series voltage data n channels by m data points per channel
% AllTime-a length m time vector in microseconds Unix Time that corresponds with AllData
% NumStims-a vector generated by findStim with the number of sub stimulation in each stim group
% 
% Output
% 
% A plot with prestimulation colored in blue, stimulation colored in purple, and post stimulation colored in red

%% Variable Input Defaults
%Instantiate inputParser
p = inputParser;

%Define minimum number of consecutive 0 slope points to make up Stimulation
addRequired(p,'Channel')
addRequired(p,'StimNumber')
addRequired(p,'StimStartIndex')
addRequired(p,'StimEndIndex')
addRequired(p,'AllData')
addRequired(p,'AllTime')
addRequired(p,'NumStims')
addParameter(p, 'Buffer',800)

%Parse inputs
parse(p, Channel, StimNumber, StimStartIndex, StimEndIndex, AllData, AllTime, NumStims, varargin{:})
Buffer=p.Results.Buffer;

%% Plot a given Stimulation
figure
hold on

%Plot the data points in the Window 
plot(datetime(AllTime(StimStartIndex(StimNumber)-Buffer:StimEndIndex(StimNumber)+Buffer)/1e6,'ConvertFrom','posixtime')...
,AllData(Channel,StimStartIndex(StimNumber)-Buffer:StimEndIndex(StimNumber)+Buffer),'k.');

%Plot the Pre Stim
% plot(datetime(AllTime(StimStartIndex(StimNumber)-Buffer:StimStartIndex(StimNumber))/1e6,'ConvertFrom','posixtime')...
% ,AllData(Channel,StimStartIndex(StimNumber)-Buffer:StimEndIndex(StimNumber)),'b-');

%Plot the PreStimulation data in the Window with Blue Lines
plot(datetime(AllTime(StimStartIndex(StimNumber)-Buffer:StimEndIndex(StimNumber)+Buffer)/1e6,'ConvertFrom','posixtime')...
,AllData(Channel,StimStartIndex(StimNumber)-Buffer:StimEndIndex(StimNumber)+Buffer),'b-');

%Highlight the Post Stimulation Window in Red
plot(datetime(AllTime(StimEndIndex(StimNumber):StimEndIndex(StimNumber)+Buffer)/1e6,'ConvertFrom','posixtime')...
,AllData(Channel,StimEndIndex(StimNumber):StimEndIndex(StimNumber)+Buffer),'r-');

%Highlight the Stimulation Portion in Purple
plot(datetime(AllTime(StimStartIndex(StimNumber):StimEndIndex(StimNumber))/1e6,'ConvertFrom','posixtime')...
,AllData(Channel,StimStartIndex(StimNumber):StimEndIndex(StimNumber)),'m-','LineWidth',5);

%Label The Graph
title(['Stimulation #',num2str(StimNumber)])
ylabel('millivolts?')
xlabel('Time (HH:MM:SS)')

text(0.8,0.2,[num2str(NumStims(StimNumber)),' Stimulations'],'Units','normalized','FontSize',16)
hold off
end

